version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
    - "80:80"
    volumes:
    - "./conf.d:/etc/nginx/conf.d"
    links:
    - node_express

  node_express:
    image: node:9.11.1-alpine
    container_name: node_express
    hostname: node_express
    command: "npm 4docker"
    volumes:
    - ".:/src"
    working_dir: /src
    ports:
    - "3000:3000"
